test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  project: <%= Rails.application.secrets.gcs[:project] %>
  credentials: <%= Rails.root.join("config/granite-454312-6f37084b5a57.json") %>
  bucket: <%= 'granite-report-01' %>
